apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: IMAGE_LABEL
    spec:
      containers:
      - name: frontend
        image: robrich/frontend:IMAGE_LABEL
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend
        resources: {}
