name: App Build

on:
  push:
    branches:
    - main
    - develop
    - 'release/**'
    - 'hotfix/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Form image tag from Git
      id: label
      run: echo "label=${GITHUB_SHA::7}-$(echo ${{ github.ref_name }} | tr / -)" >> $GITHUB_OUTPUT

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true

    - name: Docker Build & Push, GitOps push
      run: |
        echo "branch = ${{ github.ref_name }} hash = ${{ github.sha }} label = ${{ steps.label.outputs.label }}"

        export DOCKER_BUILDKIT=1

        cd apps/backend
        echo '{"hash": "${{ github.sha }}", "branch": "${{ steps.label.outputs.label }}"}' > version.json
        docker build -t robrich/backend:${{ steps.label.outputs.label }} .

        cd ../frontend
        echo '{"hash": "${{ github.sha }}", "branch": "${{ steps.label.outputs.label }}"}' > version.json
        docker build -t robrich/frontend:${{ steps.label.outputs.label }} .
        cd ../..

        docker push robrich/backend:${{ steps.label.outputs.label }}
        docker push robrich/frontend:${{ steps.label.outputs.label }}

        sed -i'' -e 's/IMAGE_LABEL/${{ steps.label.outputs.label }}/g' k8s/backend/deployment.yaml
        sed -i'' -e 's/IMAGE_LABEL/${{ steps.label.outputs.label }}/g' k8s/frontend/deployment.yaml

        git config --unset-all http.https://github.com/.extraheader
        git config --global user.name "gh-actions"
        git config --global user.email "ci@example.com"
        git clone https://user:${{ secrets.GH_TOKEN }}@github.com/${{ vars.ARGO_REPO }} argo

        cd argo
        git show-ref --verify --quiet refs/heads/${{ github.ref_name }} && git checkout ${{ github.ref_name }} || git checkout -b ${{ github.ref_name }}
        rm -rf apps
        mkdir apps
        cp -r ../k8s/* apps
        git add .
        git commit -m "${{ steps.label.outputs.label}}"
        git push origin ${{ github.ref_name }} -f
